# Generated by Django 6.0.7 on 2026-07-14 19:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_loginchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=255)),
                ('service', models.CharField(max_length=64)),
                ('params', models.JSONField(default=dict)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakdown', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='agent.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('quote', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('gathering', 'Gathering'), ('quoted', 'Quoted'), ('placed', 'Placed')], default='gathering', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drafts', to='agent.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
