# Generated by Django 6.0.7 on 2026-07-15 07:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_order_orderdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('order', 'Order'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General'), ('other', 'Other')], default='other', max_length=16)),
                ('reason', models.CharField(default='agent_handoff', max_length=32)),
                ('transcript', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='agent.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
