# Generated by Django 6.0.7 on 2026-07-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginChallenge',
        ),
    ]
